import { websiteName } from '../../../config/configuration';
import Head from 'next/head';

interface TheHeadProps {
    pageTitle?: string;
}

export const getPageTitle = (pageTitle?: string) => {
    if (!pageTitle) {
        return websiteName;
    }
    return `${pageTitle} | ${websiteName}`;
};

const TheHead = ({ pageTitle }: TheHeadProps) => (
    <Head>
        <title>{getPageTitle(pageTitle)}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    </Head>
);

export default TheHead;
